### ISSUE TITLE
关于nuscene的轨迹真值来源和nuscene生成rosbag

### ISSUE THREAD

**Issue by xuwuzhou** [kinggreat24/dv-loam#1]
nuscene数据集貌似没有提供真值轨迹文件？请问您是怎么提取的呢，另外，测试nuscene的时候，您是直接读取源文件还是生成的rosbag？如果是生成的rosbag，可以将对应的工具开源吗？

**Comment by kinggreat24** [comment]
> nuscene数据集貌似没有提供真值轨迹文件？请问您是怎么提取的呢，另外，测试nuscene的时候，您是直接读取源文件还是生成的rosbag？如果是生成的rosbag，可以将对应的工具开源吗？

nuscene数据集里面数据的信息是存在json文件里面的，他们提供了一个[dev kit包](https://github.com/nutonomy/nuscenes-devkit)，你可以去看看，图像，激光雷达等传感器都有采集的时间。我是在[nuscens2bag](https://github.com/clynamen/nuscenes2bag)基础上改的，根据图像寻找时间最相近的激光数据，以及位置信息，输出的文件是KITTI格式的，一会我把工具包上传上去。

**Comment by kinggreat24** [comment]
@xuwuzhou ，你好，工具包我已经上传到[nuscenes2kitti](https://github.com/kinggreat24/nuscene2kitti)，你可以是试试，看看符不符合你的要求。

**Comment by xuwuzhou** [comment]
好的，谢谢大佬，我试试！

**Comment by xuwuzhou** [comment]
大佬，您在论文里下载的是哪一个数据集，我看nuscene有很多数据集
![Uploading 2021-10-11 16-39-13 的屏幕截图.png…]()

**Comment by xuwuzhou** [comment]
![2021-10-11 16-39-13 的屏幕截图](https://user-images.githubusercontent.com/44218507/136760002-706a19a0-57d7-4a44-bc6e-1e9975a06328.png)

**Comment by xuwuzhou** [comment]
我目前下了mini和trainval的part1，但是感觉都不符合那个工具的文件夹格式

**Comment by kinggreat24** [comment]
![微信图片_20211011164709](https://user-images.githubusercontent.com/30688557/136760945-9dccf880-7d1a-4d60-ab56-d8885b54294f.jpg)
我就是用的train_part1啊，里面的是这样的，你看看你的是什么样的

**Comment by xuwuzhou** [comment]
![2021-10-11 16-50-54 的屏幕截图](https://user-images.githubusercontent.com/44218507/136761476-a1d0c4e8-1a10-4a02-91d1-8ca362905d6c.png)
我的长这样(将meta文件夹也放了进来)

**Comment by kinggreat24** [comment]
那应该是可以的吧  我这边没什么问题啊

**Comment by xuwuzhou** [comment]
运行一晚上发现几个问题，一是转换速度非常慢，二是出错自动停止，错误如下
![2021-10-12 10-13-52 的屏幕截图](https://user-images.githubusercontent.com/44218507/136879759-2151fa47-9e27-4278-bb4c-51a28ff2b9bd.png)

**Comment by kinggreat24** [comment]
![Screenshot from 2021-10-12 10-30-00](https://user-images.githubusercontent.com/30688557/136881184-07b48d65-7de9-474a-aa7d-91bed29aae78.png)
![Screenshot from 2021-10-12 10-30-57](https://user-images.githubusercontent.com/30688557/136881189-4d7d19a6-babc-4b26-a341-ab935fab78be.png)
我这里运行的挺正常的，这个处理确实比较费时间，因为数据量比较大，最后的结果快80G。至于你碰到的这个问题，我觉得可能是因为opencv版本的问题，或者是其它依赖项的问题，我这里用的是opencv3.2。你可以试试[nuscenes2bag](https://github.com/clynamen/nuscenes2bag)运行的有没有问题，我是在这个的基础上改的。

**Comment by xuwuzhou** [comment]
你好，我试了下原版nuscenes2bag，会出现同样的问题，估计真是依赖项的问题，另外考虑到nuscene目前没有关于里程计的榜单，所以暂时搁置了使用nuscene数据集的想法，等以后写期刊的时候再来处理这个问题，谢谢这两天的回复，这个issue我先关了
